//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FYPTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class testDB
    {
        public int id { get; set; }
        public string Surname { get; set; }
        public string Forename { get; set; }
        public string TownlandStreet { get; set; }
        public string DED { get; set; }
        public string County { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
        public string Birthplace { get; set; }
        public string Occupation { get; set; }
        public string Religion { get; set; }
        public string Literacy { get; set; }
        public string IrishLanguage { get; set; }
        public string RelationToHeadOfHousehold { get; set; }
        public string MaritalStatus { get; set; }
        public string SpecifiedIllness { get; set; }
        public Nullable<int> Religion_ID { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Long { get; set; }
        public string AddressToGeoCode { get; set; }
        public string HouseNo { get; set; }
        public Nullable<int> AmountInHouse { get; set; }
        public string OriginalCensusForm { get; set; }
        public string LocationType { get; set; }
    }
}
